name: Manual Build Artifact

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build JAR artifact
    uses: Minecraft-Mod-Development-Dear/.github/.github/workflows/forge-gradle-ci.yml@main
    with:
      java-version: "8"
      gradle-version: "4.10.3"
      build-task: build
      artifact-glob: build/libs/*.jar
